# Generated by Django 2.2.7 on 2020-09-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("rating", models.FloatField(null=True)),
                ("running_time", models.CharField(max_length=255, null=True)),
                ("genre", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(null=True)),
                ("release_date", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "movie",
            },
        ),
    ]
